// <auto-generated />
using System;
using HagaDropsIt.SQL.Store;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HagaDropsIt.SQL.Store.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HagaDropsIt.Shared.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CustomerGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ProductId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("HagaDropsIt.Shared.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("EventId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("HagaDropsIt.Shared.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Spel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tangentbord"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Datormus"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Router"
                        });
                });

            modelBuilder.Entity("HagaDropsIt.Shared.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<Guid>("CustomerGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HagaDropsIt.Shared.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = 0,
                            Description = "Välkommen till Haga It Drops lanseringsfest!",
                            EndDate = new DateTime(2024, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageURL = "Assets/images/Esport.webp",
                            Location = "Haga Drops It, Hagavägen 1337",
                            Name = "Lanseringsfest",
                            Price = 0.0,
                            StartDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 12,
                            Description = "Kom och mys med oss under bar himmel, och varför inte passa på och gamea ihop?",
                            EndDate = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageURL = "Assets/images/oldtown.webp",
                            Location = "Haga Drops It, Hagavägen 1337",
                            Name = "Mys och spel under hagas bara himmel",
                            Price = 299.0,
                            StartDate = new DateTime(2024, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriction = 12,
                            Description = "Välkommen till hagas årliga julbord!",
                            EndDate = new DateTime(2024, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageURL = "Assets/images/extraterrestrial.webp",
                            Location = "Haga Drops It, Hagavägen 1337",
                            Name = "Julfest!",
                            Price = 299.0,
                            StartDate = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HagaDropsIt.Shared.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Äventyr"
                        },
                        new
                        {
                            Id = 3,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 4,
                            Name = "MMORPG"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Platform"
                        });
                });

            modelBuilder.Entity("HagaDropsIt.Shared.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInvisible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PgRating")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("RealeaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "World of Warcraft är ett massivt onlinespel som utspelar sig i en fantasivärld känd som Azeroth. Spelet, utvecklat av Blizzard Entertainment, bjuder spelare in i en rik och levande värld fylld med äventyr, strider och möjligheter till samarbete.",
                            Discount = 0.10000000000000001,
                            GenreId = 4,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "World Of Warcraft",
                            PgRating = 1,
                            Price = 499.0,
                            RealeaseDate = new DateTime(2004, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "The Witcher 3: Wild Hunt är ett actionrollspel som utspelar sig i en öppen värld. Spelet, utvecklat av CD Projekt Red, är den tredje delen i The Witcher-serien och följer monsterjägaren Geralt av Rivia i hans strävan att hitta sin adoptivdotter Ciri.",
                            Discount = 0.10000000000000001,
                            GenreId = 3,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "The Witcher 3",
                            PgRating = 18,
                            Price = 399.0,
                            RealeaseDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Doom Eternal är ett förstapersonsskjutarspel som utvecklats av id Software och utgivits av Bethesda Softworks. Spelet är den femte huvuddelen i Doom-serien och en uppföljare till Doom från 2016.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Doom Eternal",
                            PgRating = 18,
                            Price = 599.0,
                            RealeaseDate = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "The Legend of Zelda: Breath of the Wild är ett actionäventyrsspel som utvecklats och publicerats av Nintendo. Spelet är den artonde huvuddelen i The Legend of Zelda-serien och släpptes till Nintendo Switch och Wii U i mars 2017.",
                            Discount = 0.10000000000000001,
                            GenreId = 2,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "The Legend of Zelda: Breath of the Wild",
                            PgRating = 12,
                            Price = 499.0,
                            RealeaseDate = new DateTime(2017, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Super Mario Odyssey är ett plattformsspel som utvecklats och publicerats av Nintendo. Spelet släpptes till Nintendo Switch i oktober 2017 och är den sextonde huvuddelen i Super Mario-serien.",
                            Discount = 0.10000000000000001,
                            GenreId = 5,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Super Mario Odyssey",
                            PgRating = 7,
                            Price = 499.0,
                            RealeaseDate = new DateTime(2017, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Razer BlackWidow Elite är ett mekaniskt tangentbord som är utformat för att ge spelare en överlägsen spelupplevelse. Tangentbordet har Razers mekaniska brytare, Chroma RGB-bakgrundsbelysning och en avtagbar handledsstöd.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Razer BlackWidow Elite",
                            PgRating = 0,
                            Price = 1499.0,
                            RealeaseDate = new DateTime(2018, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Corsair K95 RGB Platinum är ett mekaniskt tangentbord som är utformat för att ge spelare en överlägsen spelupplevelse. Tangentbordet har Cherry MX-brytare, RGB-bakgrundsbelysning och en avtagbar handledsstöd.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Corsair K95 RGB Platinum",
                            PgRating = 0,
                            Price = 1799.0,
                            RealeaseDate = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Razer DeathAdder Elite är en optisk spel-mus som är utformad för att ge spelare en överlägsen spelupplevelse. Musen har en 16 000 DPI-sensor, Chroma RGB-belysning och sju programmerbara knappar.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Razer DeathAdder Elite",
                            PgRating = 0,
                            Price = 699.0,
                            RealeaseDate = new DateTime(2016, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Logitech G502 Hero är en optisk spel-mus som är utformad för att ge spelare en överlägsen spelupplevelse. Musen har en 16 000 DPI-sensor, RGB-belysning och elva programmerbara knappar.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Logitech G502 Hero",
                            PgRating = 0,
                            Price = 799.0,
                            RealeaseDate = new DateTime(2018, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Asus RT-AX88U är en trådlös router som är utformad för att ge spelare en överlägsen spelupplevelse. Routern har stöd för Wi-Fi 6, dubbla band, 8 LAN-portar och en 1,8 GHz quad-core processor.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Asus RT-AX88U",
                            PgRating = 0,
                            Price = 2999.0,
                            RealeaseDate = new DateTime(2018, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "Netgear Nighthawk XR500 är en trådlös router som är utformad för att ge spelare en överlägsen spelupplevelse. Routern har stöd för dubbla band, 4 LAN-portar och en 1,7 GHz dual-core processor.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Netgear Nighthawk XR500",
                            PgRating = 0,
                            Price = 1999.0,
                            RealeaseDate = new DateTime(2018, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "TP-Link Archer C5400X är en trådlös router som är utformad för att ge spelare en överlägsen spelupplevelse. Routern har stöd för trippel band, 8 LAN-portar och en 1,8 GHz quad-core processor.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "TP-Link Archer C5400X",
                            PgRating = 0,
                            Price = 2499.0,
                            RealeaseDate = new DateTime(2018, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "Cyberpunk 2077 är ett actionrollspel som utspelar sig i en öppen värld. Spelet, utvecklat av CD Projekt Red, är baserat på Cyberpunk 2020-bordsspelet och utspelar sig i den dystopiska staden Night City.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Cyberpunk 2077",
                            PgRating = 18,
                            Price = 599.0,
                            RealeaseDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Description = "Halo Infinite är ett förstapersonsskjutarspel som utvecklats av 343 Industries och publicerats av Xbox Game Studios. Spelet är den sjätte huvuddelen i Halo-serien och en uppföljare till Halo 5: Guardians.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Halo Infinite",
                            PgRating = 18,
                            Price = 599.0,
                            RealeaseDate = new DateTime(2021, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Description = "Call of Duty: Warzone är ett förstapersonsskjutarspel som utvecklats av Infinity Ward och Raven Software och publicerats av Activision. Spelet är en del av Call of Duty: Modern Warfare och släpptes i mars 2020.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Call of Duty: Warzone",
                            PgRating = 18,
                            Price = 0.0,
                            RealeaseDate = new DateTime(2020, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Description = "Fortnite är ett överlevnadsspel som utvecklats av Epic Games och släpptes som en del av Fortnite: Save the World. Spelet är en del av Fortnite-serien och släpptes i juli 2017.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Fortnite",
                            PgRating = 12,
                            Price = 0.0,
                            RealeaseDate = new DateTime(2017, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Description = "Apex Legends är ett förstapersonsskjutarspel som utvecklats av Respawn Entertainment och publicerats av Electronic Arts. Spelet är en del av Titanfall-serien och släpptes i februari 2019.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Apex Legends",
                            PgRating = 18,
                            Price = 0.0,
                            RealeaseDate = new DateTime(2019, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Description = "Valorant är ett förstapersonsskjutarspel som utvecklats av Riot Games och släpptes i juni 2020. Spelet är en del av Valorant-serien och har en unik karaktär och spellista.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Valorant",
                            PgRating = 16,
                            Price = 0.0,
                            RealeaseDate = new DateTime(2020, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Description = "League of Legends är ett multiplayer online battle arena-spel som utvecklats och publicerats av Riot Games. Spelet släpptes i oktober 2009 och har blivit ett av de mest populära spelen i världen.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "League of Legends",
                            PgRating = 12,
                            Price = 0.0,
                            RealeaseDate = new DateTime(2009, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Description = "Counter-Strike: Global Offensive är ett förstapersonsskjutarspel som utvecklats av Valve Corporation och Hidden Path Entertainment. Spelet är den fjärde huvuddelen i Counter-Strike-serien och släpptes i augusti 2012.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Counter-Strike: Global Offensive",
                            PgRating = 16,
                            Price = 0.0,
                            RealeaseDate = new DateTime(2012, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            Description = "Minecraft är ett sandbox-spel som utvecklats och publicerats av Mojang Studios. Spelet släpptes i november 2011 och har blivit ett av de mest populära spelen i världen.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Minecraft",
                            PgRating = 7,
                            Price = 0.0,
                            RealeaseDate = new DateTime(2011, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            Description = "Among Us är ett onlinespel som utvecklats och publicerats av InnerSloth. Spelet släpptes i juni 2018 och har blivit ett av de mest populära spelen i världen.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Among Us",
                            PgRating = 7,
                            Price = 0.0,
                            RealeaseDate = new DateTime(2018, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            Description = "Genshin Impact är ett actionrollspel som utvecklats och publicerats av miHoYo. Spelet släpptes i september 2020 och har blivit ett av de mest populära spelen i världen.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Genshin Impact",
                            PgRating = 12,
                            Price = 0.0,
                            RealeaseDate = new DateTime(2020, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            Description = "Overwatch är ett förstapersonsskjutarspel som utvecklats och publicerats av Blizzard Entertainment. Spelet släpptes i maj 2016 och har blivit ett av de mest populära spelen i världen.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Overwatch",
                            PgRating = 12,
                            Price = 0.0,
                            RealeaseDate = new DateTime(2016, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            Description = "Rocket League är ett sportspel som utvecklats och publicerats av Psyonix. Spelet släpptes i juli 2015 och har blivit ett av de mest populära spelen i världen.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Rocket League",
                            PgRating = 3,
                            Price = 0.0,
                            RealeaseDate = new DateTime(2015, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 1,
                            Description = "FIFA 21 är ett sportspel som utvecklats och publicerats av Electronic Arts. Spelet släpptes i oktober 2020 och har blivit ett av de mest populära spelen i världen.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "FIFA 21",
                            PgRating = 3,
                            Price = 0.0,
                            RealeaseDate = new DateTime(2020, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            Description = "NBA 2K21 är ett sportspel som utvecklats och publicerats av 2K Sports. Spelet släpptes i september 2020 och har blivit ett av de mest populära spelen i världen.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "NBA 2K21",
                            PgRating = 3,
                            Price = 0.0,
                            RealeaseDate = new DateTime(2020, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 1,
                            Description = "Madden NFL 21 är ett sportspel som utvecklats och publicerats av Electronic Arts. Spelet släpptes i augusti 2020 och har blivit ett av de mest populära spelen i världen.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Madden NFL 21",
                            PgRating = 3,
                            Price = 0.0,
                            RealeaseDate = new DateTime(2020, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            Description = "Grand Theft Auto V är ett actionäventyrsspel som utvecklats och publicerats av Rockstar Games. Spelet släpptes i september 2013 och har blivit ett av de mest populära spelen i världen.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Grand Theft Auto V",
                            PgRating = 18,
                            Price = 0.0,
                            RealeaseDate = new DateTime(2013, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            Description = "Red Dead Redemption 2 är ett actionäventyrsspel som utvecklats och publicerats av Rockstar Games. Spelet släpptes i oktober 2018 och har blivit ett av de mest populära spelen i världen.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Red Dead Redemption 2",
                            PgRating = 18,
                            Price = 0.0,
                            RealeaseDate = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 1,
                            Description = "The Elder Scrolls V: Skyrim är ett actionrollspel som utvecklats och publicerats av Bethesda Game Studios. Spelet släpptes i november 2011 och har blivit ett av de mest populära spelen i världen.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "The Elder Scrolls V: Skyrim",
                            PgRating = 18,
                            Price = 0.0,
                            RealeaseDate = new DateTime(2011, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 1,
                            Description = "The Legend of Zelda: Ocarina of Time är ett actionäventyrsspel som utvecklats och publicerats av Nintendo. Spelet släpptes i november 1998 och har blivit ett av de mest populära spelen i världen.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "The Legend of Zelda: Ocarina of Time",
                            PgRating = 7,
                            Price = 0.0,
                            RealeaseDate = new DateTime(1998, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 1,
                            Description = "Super Mario 64 är ett plattformsspel som utvecklats och publicerats av Nintendo. Spelet släpptes i juni 1996 och har blivit ett av de mest populära spelen i världen.",
                            Discount = 0.10000000000000001,
                            GenreId = 1,
                            ImageURL = "Assets/Products/Phoenix Stream Console.webp",
                            IsInvisible = false,
                            IsNew = false,
                            IsOnSale = false,
                            Name = "Super Mario 64",
                            PgRating = 3,
                            Price = 0.0,
                            RealeaseDate = new DateTime(1996, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 100
                        });
                });

            modelBuilder.Entity("HagaDropsIt.Shared.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("HagaDropsIt.Shared.Entities.Cart", b =>
                {
                    b.HasOne("HagaDropsIt.Shared.Entities.Event", null)
                        .WithMany("Carts")
                        .HasForeignKey("EventId");

                    b.HasOne("HagaDropsIt.Shared.Entities.Product", null)
                        .WithMany("Carts")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("HagaDropsIt.Shared.Entities.CartItem", b =>
                {
                    b.HasOne("HagaDropsIt.Shared.Entities.Cart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("CartId");

                    b.HasOne("HagaDropsIt.Shared.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("HagaDropsIt.Shared.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Event");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HagaDropsIt.Shared.Entities.Customer", b =>
                {
                    b.HasOne("HagaDropsIt.Shared.Entities.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("HagaDropsIt.Shared.Entities.Product", b =>
                {
                    b.HasOne("HagaDropsIt.Shared.Entities.Genre", null)
                        .WithMany("Collection")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HagaDropsIt.Shared.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("HagaDropsIt.Shared.Entities.Event", b =>
                {
                    b.Navigation("Carts");
                });

            modelBuilder.Entity("HagaDropsIt.Shared.Entities.Genre", b =>
                {
                    b.Navigation("Collection");
                });

            modelBuilder.Entity("HagaDropsIt.Shared.Entities.Product", b =>
                {
                    b.Navigation("Carts");
                });
#pragma warning restore 612, 618
        }
    }
}
